### ISSUE TITLE
purchase and apply new domain for production

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#140]
The launch demo will happen on the Kartoza production server on 1 July (cc @lucernae @timlinux)

We need a good permanent domain name for this (in addition to geonode.kartoza.com). Something ideally with 'geosafe' and possibly 'gfdrr' as well. 

start by identifying some available options

It needs to be purchased and in place by Monday 26 June.

**Comment by boney-bun** [comment]
cmiiw, this ticket is about buying a domain name for the production server. am i right?
or, does the ticket include a hosting server too?
is it okay if the domain names options being listed here? 
or, should i post in gitter instead @gubuntu ?

**Comment by gubuntu** [comment]
please list your selection of available domain names here

**Comment by boney-bun** [comment]
as a start, these are on my mind:
## geosafe.com
already taken by google. need at least $3,500 to take over the domain
## geosafe.org  ($13.99)
* the GFDRR site is gfdrr.org, so we may consider using .org too.
* the drawback is the users might end up going to geosafe.com instead. 
* the users need to be accustomed to this address. otherwise, they can be misleaded to the other website.
* or, we can consider using: gfdrr.geosafe.org 
## gfdrr-geosafe.com ($12.99)
## geosafe-gfdrr.com ($12.99)
## geosafe-gfdrr.org ($13.99)
## geosafe-gfdrr.net ($13.60)
## geosafe-gfdrr.ngo ($64.99)
## geosafe-gfdrr.community ($29.99)
## geosafe-kartoza.com ($12.99)
* can also be: gfdrr.geosafe-kartoza.com
## kartoza-geosafe.com ($12.99)
* alternatively: gfdrr.kartoza-geosafe.com

note: the price quotation is based on whois.net

**Comment by gubuntu** [comment]
thanks @boney-bun 

Do you want to go for any of these @cgiovando?

**Comment by gubuntu** [comment]
ping @cgiovando

**Comment by cgiovando** [comment]
I'm thinking geosafe-gfdrrlab.org or geosafe.geonode-gfdrrlab.org (which would be under a domain we already own). I will confirm tomorrow or Thursday at the latest.

**Comment by boney-bun** [comment]
can we close this ticket @gubuntu ?

**Comment by gubuntu** [comment]
no, we don't have the domain yet

**Comment by gubuntu** [comment]
staging.geonode.kartoza.com will alias to geonode.kartoza.com and that will be the demo server. 

geonode.ingc.gov.mz is the production server. 

we can re-open or create a new issues if more domains are required in future
