### ISSUE TITLE
We should list duration of analysis

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#147]
In the analysis list please show the duration of each analysis. It will be useful for debugging slow processing workflows and help to manage user expectations as to how long they should wait for their jobs.

<img width="829" alt="screen shot 2017-06-24 at 10 00 50 pm" src="https://user-images.githubusercontent.com/178003/27511659-541c9baa-592a-11e7-95f8-65582fbe9cb4.png">

**Comment by boney-bun** [comment]
we may add the duration of elapsed time.
but i'm not sure we can easily measure expected time.

**Comment by gubuntu** [comment]
definitely just elapsed time. This is hopefully available as part of what is returned from the inasafe analysis.

**Comment by boney-bun** [comment]
i imagine using timer with js or django.
I don't know if the backend has timer for it.
or, probably the inasafe analysis record the start and stop time.
I would look into it.

**Comment by lucernae** [comment]
Sorry I didn't read this before.
What I already implemented is:

- Create a hard time limit on celery job. For example, at the moment I set the time limit to 10 mins. If it exceeded, the job will terminate itself. In the analysis, user will see the task fails because of time limit. The reason why we had to create a time limit is, so that new job can be executed.
- Made options in the analysis list to, rerun analysis (showed up only, when it failed) or cancel analysis (showed up when the task is still running or pending). Canceling the task will terminate the job if it is running at that time, as well as deleted the analysis entry.

For the duration, I need more details. The simplest solution I can suggests is, just track celery running time and saved it into analysis model, like @boney-bun said. This way, we don't have to deal with InaSAFE. The details that I need is, do we need to track it right after user start analysis (hide user from details complexity), or only when celery worker takes the job (provides more granularity, but maybe not so important for some users)?
Possible scenario would be, if we have 4 analysis job and only 2 workers, then the last job will have to wait for any worker to finish, even if it doesn't do anything, so the duration might be misleading.

**Comment by lucernae** [comment]
And I have to add that the spirit of celery is they tried to decentralized and hides complexity.
So, in the docs somewhere, I've read that they suggests only told 3 state for user: pending, failed, and finished. But, it is possible to know when the task is started.
This is also the same case if we want to know the size of the workers connected with broker.

**Comment by gubuntu** [comment]
Thanks @lucernae. It might be useful to store two times: complete 'user time' from start to finish, i.e. how long they had to wait. Then 'process time' i.e. celery time. 

But this task is low priority this week.
