### ISSUE TITLE
click on markers or bounding boxes

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#155]
show name of layer

zoom to layer too

and decrease the zoom level that markers switch to bounding boxes. i.e. make boxes come on sooner

**Comment by boney-bun** [comment]
markers are now clickable.
a layer name will show up when hovering over the layer.
the only problem is: i can't add text to the boxes due to different version of leaflet.
I tried to use `tooltip` class, but it failed to be recognized in the browser.
it turns out that the geonode use `leaflet.fullscreen.js` (seems to be a leaflet plugin). 
there is no `tooltip` function in this library.
possible solutions:
* use `leaflet.js` instead of `leaflet.fullscreen.js` -> need to modify bower.rc and gruntfile.js on the geonode repo. **UPDATED: we do use old leaflet.js, the version is 0.7.7**
* manually add the tooltip function to the geosafe lib so we can use them -> we need to revise this function when we decide to upgrade the leaflet.
* develop our own label  implementation.

i prefer using the first option.
if this is not the case, the second option can be an alternative solution.
what do you think @gubuntu @lucernae ?
![tooltip155](https://user-images.githubusercontent.com/4602383/27835672-32a6806a-6106-11e7-9e44-09094fe69e55.gif)

**Comment by lucernae** [comment]
Hi @boney-bun thank's for investigating this, I did some review and in L.version geonode indeed uses an old fork of leaflet (v 0.7)
This leaflet came from django-leaflet package and it might be used anywhere else in the code (we have to make sure upgrading makes it consistent).
What I suggest is to use option 1, but don't change bower.rc and gruntfile.js. We can avoid that because GeoSAFE is our own repo, we can use a different leaflet version in one page as long as it doesn't conflict. So the technical way you can try is:

- delete leaflet library calls (which is coming from geonode's leaflet version) `{% load leaflet_tags %}`
- Replace `{% leaflet_css %}` calls with your own version of choice. You can get it from CDN maybe, or just include it in GeoSAFE static files
- Do the same with above, for `{% leaflet_js %}` tags.
- Confirm that all interaction in the page still behaves the same. I hope it doesn't change much, since leaflet is somewhat a stable library. But check in the browser console.log for errors.

**Comment by boney-bun** [comment]
Hi @lucernae 
i've implemented them on my local now.
the obvious impact using the new leaflet (the latest one: 1.1.0) is : we have to specify the z-index on all layers and `<div>`. 
otherwise, they won't show up on the UI because getting obstructed by the map.

**Comment by boney-bun** [comment]
what do you think of the interface @gubuntu ?
the layer names appear on hovering.
![markersclickable155](https://user-images.githubusercontent.com/4602383/28110117-86951edc-671b-11e7-9819-c081d3762437.gif)

**Comment by gubuntu** [comment]
very nice
