### ISSUE TITLE
should not change extent on Run

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#157]
Zooms out after clicking Run rather than staying at the extent that the user set, if the user zoomed into a smaller area. 

(So which extent gets sent for analysis?)

**Comment by boney-bun** [comment]
at first, i thought adding a variable to save current extent on the UI could fix the problem.
it turns out it doesn't work as expected.
i'd added a variable in AnalysisCreationForm, but it didn't reliable enough.
so, i am thinking to add a variable in `Analysis` model for saving the current extent into a more persistent state.
Looking at `geosafe.models.Analysis`, there are two disabled choices: `HAZARD_EXPOSURE_BBOX_CODE` and `HAZARD_EXPOSURE_BBOX_TEXT`. 
what is the purpose of these two options?
do we have a plan to keep the current user extent on the backend in the future @lucernae ?

**Comment by boney-bun** [comment]
the new implementation has given the extent information to the user.
all i need to do is to zoom to this extent after running an analysis.
what do you think @gubuntu @lucernae ? 
![extentrun157](https://user-images.githubusercontent.com/4602383/27793815-bc11876a-6029-11e7-94b4-fada6bb2d044.gif)

**Comment by gubuntu** [comment]
the extent is already set by the user, surely it can just stay there and not change? 

When I demo'd on Friday it zoomed out after hitting Run and then zoomed back afterwards to the correct extent. So all that needs to be fixed is not to zoom out in between.

**Comment by boney-bun** [comment]
with this commit, after run is clicked, it zoomed to the nearest layer extent, instead of staying to the user extent. 
previously, it zooms out to the widest extent. it won't return to the user extent. 
does this behaviour acceptable?

**Comment by gubuntu** [comment]
no, there should be no change as per https://github.com/kartoza/geosafe/issues/157#issuecomment-313297321

**Comment by gubuntu** [comment]
why does the map redraw at all after clicking Run, it seems unnecessary
