### ISSUE TITLE
Create analysis layer lists should respect user rights

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#178]
At the moment we can see all layers in hazard / exposure etc in create analysis page even if the user does not have rights to view them. Please fix. Eg on production server we have made user training and assigned some layers e.g. tandale_floods which are not viewable by anonymous, but the still show up in the create analysis page.

<img width="608" alt="screen shot 2017-06-30 at 11 03 18 pm" src="https://user-images.githubusercontent.com/178003/27754065-bf8872b6-5de8-11e7-94b3-eba7c9bb0b6b.png">

**Comment by akbargumbira** [comment]
Hi @timlinux, should be fixed by this commit https://github.com/kartoza/geosafe/pull/188/commits/84ce69c2d37602497f2ac727d466d8d54a782a40
in this PR https://github.com/kartoza/geosafe/pull/188

Sorry two issues on 1 PR. I forgot the habits :)

**Comment by boney-bun** [comment]
this ticket will have a few impacts in other stuff on geosafe  @timlinux @gubuntu 
I thought geosafe doesn't restrict anonymous users.
we might need to agree the logic for the current implementations:
* anonymous users can use meta search. they can even add layer to the geosafe.
* anonymous users can access Analysis list. they can download, but can't save.
* anonymous users can access Create Analysis, but a constant warning appears on the bottom page. they can't save the analysis summary

a simple fix probably is removing the geosafe menu when a user not sign in. 
but, this solution can be hacked easily, particularly if a user figure out the address link.

**Comment by lucernae** [comment]
thanks @boney-bun @akbargumbira .
yes we should agree on that.
At the moment, let's just consider that these are true:

- List of available layer is filtered by object permission of the user (I think this is fixed by @akbargumbira 's commit)
- Anon user can still create analysis (because they are given only layer available for them). But they can't save analysis (retain the analysis result). But they can download the result if they want.
- Prevent create analysis form from DDOS. (already implemented using csrf token)
- Restrict meta search add layer functionality is a good suggestion (haven't implemented yet). Only superadmin can add layer from other geonode instance?
- Limit how many number of analysis from Anon user can be kept for a day? Need more feedback on this.

CC @gubuntu @timlinux

**Comment by gubuntu** [comment]
Let's get this into staging and test and think about.

**Comment by gubuntu** [comment]
I'm taking this into backlog, not high priority for delivery of Component 4 and there doesn't appear to be anything to deploy yet.

**Comment by gubuntu** [comment]
duplicate of #81?

**Comment by gubuntu** [comment]
also related to #242 and #327

**Comment by NyakudyaA** [comment]
From my testing I see the layer permissions are being filtered accordingly in Geonode and hence they filter to GeoSAFE. If a user doesn't have permissions to view the layer it won't even appear in his Geonode layer list and hence nothing appears in Geonode. 

I think we can close this issue
