### ISSUE TITLE
Celery problem

### ISSUE THREAD

**Issue by fanevanjanahary** [kartoza/geosafe#234]
Hello, 

I’m trying to install docker-geosafe on my machine. I followed the ansible script https://github.com/kartoza/docker-geosafe/tree/develop/deployment/ansible#geonode-with-qgis-server-backend-and-geosafe 

I got on error about leaflet css not found, I fixed like this: 
```
diff --git a/templates/geosafe/analysis/detail.html b/templates/geosafe/analysis/detail.html 
index ff75f64..0e5a202 100644 
--- a/templates/geosafe/analysis/detail.html 
+++ b/templates/geosafe/analysis/detail.html 
@@ -1,5 +1,6 @@ 
{% extends 'geonode_base.html' %} 
{% load bootstrap_tags %} 
+{% load leaflet_tags %} 
{% block extra_head %} 
{% leaflet_css %} 
```

I try to run an analysis on geosafe, but celery is not working:
![capture d ecran de 2017-09-20 18-57-09](https://user-images.githubusercontent.com/12623986/30654100-9a40225a-9e35-11e7-95f2-6cde5e4688b5.png)

I don’t know how to fix this. 

Thanks

**Comment by lucernae** [comment]
> I got on error about leaflet css not found, I fixed like this:

Thank's for pointing this out, we will make a fix.

From the looks of it in the error detail, it seems the analysis extent is too big for InaSAFE to process.
I suggest you try to decrease the extent to make sure it is working.
Try zooming in into a city as much as possible to make the extent smaller (In Create Analysis Page), then run the analysis.

You can also try these to show me the logs:

- If you are using PyCharm, then I knew you already use Run/Debug Configuration features. You can see Run Logs in this window here (just click InaSAFE Headless Analysis, the process which run the analysis)

<img width="1406" alt="screen shot 2017-09-21 at 10 49 04" src="https://user-images.githubusercontent.com/831865/30678185-ab551f7a-9eba-11e7-883e-706e2f84a211.png">

This is an example of successful Analysis Log

- If you are not using PyCharm, then you probably run the whole thing in Production mode. In this case, you can go to `/deployment` folder, and run this make command from that folder:

```
make inasafe-headless-analysis-log
```

There are several `-log` commands in that `/deployment/Makefile` for you to use if you're interested.

**Comment by fanevanjanahary** [comment]
I tried with a smaller data but it's still the same error
![capture d ecran de 2017-09-21 07-02-41](https://user-images.githubusercontent.com/12623986/30678683-adcfa5d6-9e9c-11e7-9626-612bb7c9a371.png)

My logs: 
![capture d ecran de 2017-09-21 07-15-24](https://user-images.githubusercontent.com/12623986/30678712-cba66bd0-9e9c-11e7-9f2a-3643264b1da5.png)

**Comment by lucernae** [comment]
Thank's @Fanevanjanahary!
Actually, this is a very useful information for us. We know we have this issue from time to time, but can't reliably replicate it to debug this and solve it completely.

Can we have your smaller dataset (hazard and exposure), that you use in the last analysis for us to test?

# As for the explanation:

I can see in the logs that the analysis is being run (so your configuration is correct), but when it is finished, it tries to create the report but failed to do so. This is because we had some issue with QGIS containers if we try to run it headlessly. We are using Xvfb as virtual screen buffer but QGIS code itself apparently doesn't use multithreaded code cleanly. That explains this part:

```
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called.
```

Because the analysis process run in celery and it is automatically fork a new thread to run the task, we can't avoid the multi-threaded client. We have to somehow find a way to restart the worker automatically when this happens.

# The (temporary) fix:

First, you can try execute:

```
make restart-celery
```

If the same problem stills happen in the log, or the Xvfb failed to restart. Then we need to restart the whole stack:

```
make reset
```

Please tell us if it works and what steps did you take?
I'm actually impressed you are able to follow the guide, because sometimes our internal team are also having a hard time following it 😄.

**Comment by gubuntu** [comment]
@Fanevanjanahary do you need a development environment?

If you just need a production environment then rather try our latest Rancher recipe at https://github.com/kartoza/docker-geosafe/blob/develop/deployment/production/docs/Rancher.md

**Comment by gubuntu** [comment]
@Fanevanjanahary @lucernae is this still an issue? Please comment or close
