### ISSUE TITLE
analysis page does not respond to browser resize

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#256]
even in a desktop browser it is unresponsive. The only way to get it to resize is to reload the page.

**Comment by boney-bun** [comment]
i think this is no longer an issue.

![geosafe 256](https://user-images.githubusercontent.com/4602383/45537785-7161ab00-b82f-11e8-98f1-b31e9bebe500.gif)

**Comment by gubuntu** [comment]
not that paage @boney-bun the Create Analysis page

**Comment by boney-bun** [comment]
the Create Analysis page is made without considering the difference in browser size from the beginning.
so this issue will need a lot of time to finish.

are you sure we would like to do this now?

**Comment by gubuntu** [comment]
@boney-bun OK move this to the bottom of the Ready column and continue with the next issue

**Comment by gubuntu** [comment]
related to #177

**Comment by lucernae** [comment]
@gubuntu We observe it indeed follow some responsive design (although not all, because it was not planned), when we load it in device mode (using web console). But browser resize will not work, you had to reload. Because leaflet is not responsive in the first place, we either had to detect browser resize event and reload/resize leaflet accordingly. but that seems problematic for a feature that people rarely uses.

**Comment by gubuntu** [comment]
OK, won't fix
