### ISSUE TITLE
Extend GeoSAFE to support custom displacement rates

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#294]
Currently GeoSAFE uses default displacement rates for flood. We need to incorporate Mozambique specific displacement rates into the platform - first into InaSAFE and then into GeoSAFE. We propose to do this by syncing the InaSAFE definitions folder into GeoNode using Resilio so that we can easily tweak displacement rates on our desktops and deploy to the production server. Alternatively we can use a separate git submodule.

child of #306

**Comment by gubuntu** [comment]
@raisserafael will create these in InaSAFE desktop and supply the file. 

Please deploy this as the default displacement rates in Mozambique GeoSAFE.

Also document / implement a way to update them - via btsync or web form?

**Comment by gubuntu** [comment]
[Moz_minimal_needs.json.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46c59b801c8f8aa786e4be4f9b53f5912d5569793a0bad693cc7f33ab0487e021b4d44be44500e46a8f1df7ff2b76975df5c5ebfd16d5920c16915a9aa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4c39190d188aff5932a69e5985.zip)

**Comment by gubuntu** [comment]
[Moz_displacement_rates.org.json.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46c59b801c868aba9fe5be40a150f59a3d7935723d01b0657f97e466b551740f4d435cec03070511afbd9b21b4b33421880803bb85395e21c36811f9ea821fb955bd748f4a97aaaec81d9ebc6278bec1da0d2c14171981f55c30a39e4cc058f548e54b53a0017b.zip)

**Comment by gubuntu** [comment]
@lucernae will you get to this? If not @myarjunar please pick up

**Comment by gubuntu** [comment]
implement in ingc theme settings

**Comment by lucernae** [comment]
How do we test this?
I applied minimum needs and displacement settings on testing server, but don't know how to test it from the site.

**Comment by myarjunar** [comment]
@lucernae run 2 analysis with same exposure and hazard layer but with different displacement and minimum needs setting maybe? the table report should give a different result.

**Comment by gubuntu** [comment]
look at some of the values in the new docs that are different to the originals and see if they are being used?

Can we accommodate PT versions of these? If so I will create tickets for Jose to generate them.

**Comment by lucernae** [comment]
CMIIW the displacement rate should be independent of locale, but minimum needs depends on locale, like I mentioned here: #293

**Comment by gubuntu** [comment]
both can be customised therefore both are instance-specific. 

So if there's a custom version of either in the theme project it will be used. 

Locale will only come into switching languages, right?

**Comment by lucernae** [comment]
Yes, to clarify my comments above, both can be customized, but displacement rate should be independent of locale (language settings), because there are no strings there. Meanwhile minimum needs were applied depending on the locale of the analysis used (because there maybe locale specific strings in the minimum needs descriptions).

For example, this is my test data with GeoSAFE (default displacement rate, too small for test data).

Default displacement rates:
[Analisis Moz needs_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46c99a9b2f8b90a09ca9924cbe1dfe912c42344c3d05a12775c7af6aaf50740b0a0c0abe4b4a5a4cadfbdd23f0e26871df595eed843f5f74c06916f8bc870da313f871d51bdaebe5c01982fa3737e683854e3b1a041d8bf7583ca19943cf4abb.pdf)

Modified displacement rates ( rates were exaggerated to 100%):
[Analysis Moz Needs modified_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46c99a9b2f9b90a09ca9924cbe1dde912c423433240ba722768ce62c80567a03030a5cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fc95df443e74c52a7103f71ab.pdf)

Screenshots of changes:

# Default rates (small)

Displacement rates shown:

![Screen Shot 2018-11-07 at 01.24.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a378ee0c2955415e4bbe5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc59f349e94a54a1163065f43b.png)

Minimum needs shown:
![Screen Shot 2018-11-07 at 01.24.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a378ee0c2955415c4bbe5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecc59f349e94b5ca1143f6bf43b.png)

# Modified rates (100%)

Displacement rates shown:
![Screen Shot 2018-11-07 at 01.27.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a378ee0c2956415d4ebe5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c33aa984ecc59f349e94550a1133361f43b.png)

Minimum needs shown:
![Screen Shot 2018-11-07 at 01.32.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f46b7191a378ee0c2853415e47be5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecc59f349e84c52a4133161f43b.png)

**Comment by lucernae** [comment]
In summary, the settings override works as expected. In the testing and (soon) production instance, it will use inasafe settings (displacement rate) defined in custom theme app.

**Comment by gubuntu** [comment]
excellent!
