### ISSUE TITLE
make the ability to run a GeoSAFE analysis role-based

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#327]
Add permission group in geonode to be able to run geosafe analysis

(Maputo site visit feedback)

see with #242

**Comment by gubuntu** [comment]
@NyakudyaA please check if layer permissions go through to GeoSAFE

**Comment by NyakudyaA** [comment]
Yes layer permissions are respected in GeoSAFE. If a user does not have permisions to view the layer then it will not appear in his layer list and hence in GeoSAFE.

* Flood maps is not visible because the user has no permisions
![screenshot 2018-10-11 at 12 10 28](https://user-images.githubusercontent.com/2510900/46797175-b99cbc00-cd4e-11e8-8e38-194d9c08a0b5.png)

* When the admin user is added with all the permissions all layers are visible.
![screenshot 2018-10-11 at 12 11 39](https://user-images.githubusercontent.com/2510900/46797245-ebae1e00-cd4e-11e8-8860-527c07e5faee.png)
