### ISSUE TITLE
INGC theme config

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#381]
from @cgiovando
>Why is the theme code managed in a separate repository? Can you clarify the repos and steps involved in setting up the whole system?

**Comment by lucernae** [comment]
Okay @gubuntu .
GeoSAFE is supposed to be independent of the skin being used because some people may want to put different skins. Thus the skin is on separate repo.

The benefit:

1. When GeoSAFE is stable, you just need to perform changes in INGC theme repo if you want to apply skin changes (logo, text, etc). You don't need to change main GeoSAFE base.

2. If two instance of GeoSAFE use two instance of skins, they can just apply the changes for their respective skins repo. It will not affect the other (which probably belong to different organizations or divisions)

3. Localizations and Organizations specific settings can be put on the skin repo. That organizations only needs to translate language specific for their needs. It will not clash with other org

4. Theme app are made as a django app. Technically speaking, in the orchestration it is installed as python package using pip with desired package URL. You can change the skin easily by changing the url of the theme you want to install. The URL will be asked as a Rancher question, when you do update or deployment. Attached below the screenshot of said question:

![Screen Shot 2018-10-11 at 14.49.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54d0705f7637910300055208/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f26b7191a379eb0c2f58415f49be5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb51f44fe54c53a51b3564f43b.png)

5. As a side note, because it is just a theme app. I recommended to use just the repo URL to install the app, instead of deploying the package as actual python app on python package repository like Pypy. This is in the sense that no other people will use the theme app besides that organization. It is also easier to maintain the release using just a git tag, instead of deploying it as python app distributions.

**Comment by gubuntu** [comment]
thanks @lucernae 

fyi @cgiovando
