### ISSUE TITLE
Add bounding box for each layer available

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#40]
Show extent on the map

**Comment by lucernae** [comment]
Could you explain what this is again @timlinux ?

```
3) As an experiment, add bounding boxes for each layer that is available
```

**Comment by gubuntu** [comment]
On popup of hazard or exposure layer selection dialog, draw each available layer's bounding box (BB) on the map (and zoom out to all) and as you hover over each layer, pulse or highlight its BB. Or colour each BB differently and match  layer text colours to BB colours. 

Once a layer is selected, resume previous zoom behaviour.

**Comment by boney-bun** [comment]
before #101 , every time a layer is selected, the map will zoom-in according to the selected layer.
as of #101, I have disabled the zoom in feature every time a layer is chosen. the zoom-in only works once at the first selected zoom and won't do another zoom afterward.
is this kind of behaviour that you meant @gubuntu ?

**Comment by gubuntu** [comment]
No

#101 should not have affected zoom behaviour - please revert that 

This issue is about drawing bounding boxes, zooming is secondary.

**Comment by gubuntu** [comment]
consider using centroid markers at small scales or if layers get too dense

**Comment by gubuntu** [comment]
consider using centroid markers at small scales or if layers get too dense

**Comment by boney-bun** [comment]
I would revert the zoom behaviour on a separate commit (the one that is related to #101).
please let me know what do you think of the proposed drawing bounding boxes @gubuntu.
![bounding-box40v2](https://user-images.githubusercontent.com/4602383/27191452-0306b4bc-5222-11e7-88de-4c634c3765df.gif)
by default, both layers are shown by the markers. 
when the zoom level is more than 10, the hazard layers are shown by black rectangles on the map. whereas the exposure layers are represented by orange rectangles. 

UPDATED (a slower version of gif, but smaller resolution due to size restriction):
![addboundingbox40v2](https://user-images.githubusercontent.com/4602383/27334330-2d63130c-55f3-11e7-807d-99bbe32fcff4.gif)

**Comment by gubuntu** [comment]
looks very nice @boney-bun but it's hard to see the exact behaviour here. Maybe slow the gif down?
- the marker or bounding box (depending on scale) of all hazard and all exposure layers must draw whether you've chosen a layer or not
- only the layer bounding box must render, not individual polygons nor the bounding boxes of individual polygons
- what happens after you've chosen a hazard or exposure layer? I think the original behaviour should continue in addition to the new bounding boxes.

**Comment by boney-bun** [comment]
please see the updated and slower version in the previous comment @gubuntu 
three layers are drawn where  the two layers almost closely locate together.
the layer bounding box indeed shows the group of polygons, not the individual ones. 

once a layer is selected, both the marker or bounding box will disappear and the behaviour will resume as in the current implementation. 

i've tried to keep the bounding box even after a user selects a layer. but, the bounding box will overlap with the selected layer itself and may obstruct its appearance. that's why the marker or bounding box disappear when the user has selected a layer.

**Comment by gubuntu** [comment]
The markers look good on staging but I don't see any bounding boxes at any scale

**Comment by boney-bun** [comment]
the bounding boxes show up when the zoom level is larger than 10.
apparently, the level should be lower so we can see them on the staging.
I would set the zoom level to 5.
![boundingbox40](https://user-images.githubusercontent.com/4602383/27514188-d38f50ee-59ac-11e7-9646-86d830e56bcb.gif)

**Comment by gubuntu** [comment]
OK. Can you also increase the transparency till it's very faint or make them just boundaries (no fill). We just need a cue as to where the data layers are without obliterating the background.

**Comment by boney-bun** [comment]
the rectangle has no fill now.
i think it doesn't obstruct the background.
![boundingbox40](https://user-images.githubusercontent.com/4602383/27517638-fa2824a4-59f9-11e7-8262-447892ef8731.gif)

**Comment by gubuntu** [comment]
that one is perfect. I was looking at the orange ones in your previous gif.

**Comment by boney-bun** [comment]
below is another illustration with orange and blue bounding box
![addboundingbox40](https://user-images.githubusercontent.com/4602383/27590275-5d01d442-5b78-11e7-8ddf-0fc5e1d4a2a4.gif)

**Comment by gubuntu** [comment]
looking better. Please get this and other work from the last few days merged and deployed on staging in the next few hours or is it already there?

**Comment by boney-bun** [comment]
i'll go and merge then.
