### ISSUE TITLE
hazard layers are not styled and flood has no metadata

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#438]
- [x] Styling hazard layers
- [x] Adding metadata to Flood

**Comment by NyakudyaA** [comment]
@raisserafael must have uploaded a new flood layer. He showed me a new flood layer. will look at it now.

For now I will remove clyclones from Hazard layers and just make them Geonode layers because they are not supported. 

@raisserafael was supposed to do the styling and add more flesh to the metadata ie Abstract for layers without. will take over the styling. 


This will leave us with only 1 hazard layer
