### ISSUE TITLE
affected = 0 and hazard area breakdown order

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#446]
![Screenshot 2018-11-07 at 15.35.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7953e32a64c5b27df1112e4f5c5b5cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc95dff4ce94d54a5143271ab.png)

**Comment by myarjunar** [comment]
I inspect the impact layer and found that every features in the impact layer has affected field equal False which means total affected = 0 is reasonable. I believe there are some mistakes in the keywords generation either in the hazard layer or exposure layer. 

Otherwise, my concern is with the hazard area breakdown in the popup report, it looks dodgy. we need to show it in proper order.

**Comment by gubuntu** [comment]
> I inspect the impact layer and found that every features in the impact layer has affected field equal False which means total affected = 0 is reasonable. I believe there are some mistakes in the keywords generation either in the hazard layer or exposure layer.

@NyakudyaA please investigate - the data and keywords must be correct, accurate and trustworthy

> Otherwise, my concern is with the hazard area breakdown in the popup report, it looks dodgy. we need to show it in proper order.

@myarjunar yes that is an issue - the classes must definitely be ordered

**Comment by NyakudyaA** [comment]
@gubuntu I will investigate. I will have a chat with Jose. When I took over the metadata uploading I did so with the hope that Jose knew what he was doing and just uploaded the keywords. But will look at each of the layers especially the hazard layer.

But hope the Earthquake I uploaded today worked well in the demo with realistic results
