### ISSUE TITLE
not zooming into impact layer extent

### ISSUE THREAD

**Issue by myarjunar** [kartoza/geosafe#458]
noot zooming into impact layer extent when hazars or exposure layers are being selected.

**Comment by boney-bun** [comment]
it seems that the behaviour is expected.
as a user chooses hazard, exposure, (optionally) aggregation, and impact layers, the user will also zoom into a specific area based on the user's interest. then, he will click the `Run` button.
after the analysis finished, geosafe will show the user's area selection instead of impact layer.

**Comment by gubuntu** [comment]
I think the behaviour is to zoom into the extent of the last layer chosen. @myarjunar try to elaborate on what you think is the actual problem here.

**Comment by gubuntu** [comment]
lack of feedback
