### ISSUE TITLE
The status bar at the bottom of the screen is not obvious enough

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#46]
The status bar at the bottom of the screen is not obvious enough.
figure out a way to make the messages more prominent...

**Comment by lucernae** [comment]
Actually I'm bad at figuring out this kinds of things. 😄 
Any other suggestion on this?
Perhaps we can limit the message to only for important one?
Like filtering layer is almost always happen, so omit filtering layer message?

@gubuntu @timlinux

**Comment by gubuntu** [comment]
perhaps pulse them quite large and bright when they change, to catch the users eye. 

And make their normal static display a bit bright or more contrasting and put a standout border around the status area?

@timlinux perhaps you can elaborate

**Comment by boney-bun** [comment]
this is probably a subjective and personal matter.
imho, the current status bar has already attracted the users attention.
the status bar sometimes change colour as the user interact with geosafe. 
if we do want to add an element to the status bar for getting an attention from the user, we can consider using a constant blink colours. 
or, we can move the status bar to the top of the window, instead of at the bottom.

**Comment by gubuntu** [comment]
@lucernae I think we can close this
