### ISSUE TITLE
add keywords to cyclone layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#479]
we need to be able to use these as hazards in GeoSAFE

**Comment by NyakudyaA** [comment]
It turns out had a lot to figure out on these layers. There was something about the layers loaded that was not working. Tried downloading and then upload again with keywords and the layers had gdal errors. Had to translate them again and then load them again.

![cyclone](https://user-images.githubusercontent.com/2510900/48558462-03e6ff00-e8f2-11e8-83e1-7e0251c4abb1.png)
 
Now all the layers are appearing in GeoSAFE

**Comment by gubuntu** [comment]
well done, thank you!
