### ISSUE TITLE
extra papercuts

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#48]
- [x] when not logged in I am warned that analysis will not be saved, yet it does get saved. 
- [x] dont'save / save just switch between each other and the dialog only disappears when clicking somewhere else
- [x] Change home page button hover to 'To home page' from 'to geonode home page'
- [x] Once an analysis has bene Saved, why does the Save button keep appearing?
could?) be affected' (or 'what Stellenbosch Population')

**Comment by lucernae** [comment]
> - [ ] when not logged in I am warned that analysis will not be save, yet it does get saved. 

Yes it will be saved but will be deleted the day after. This is one of the original spec. The reason is, anonymous user should be able to run analysis, but should not be able to keep them. admin user can choose between the option.

> - [ ] dont'save / save just switch between each other and the dialog only disappears when clicking somewhere else

See above, this is because it is just a toggle to mark, either the analysis should be kept or not for the day onwards.

> - [ ] Change home page button hover to 'To home page' from 'to geonode home page'

I can do this quickly

> - [ ] Once an analysis has bene Saved, why does the Save button keep appearing?

Ah yes, maybe it is a bit confusing for this representations. So, in the ticket I suggest that we should change this to a checkmark or something, so the user know that this is an option, not action.

> - [ ] Improve Anaysis Result English. 'In the event of Stellenbosch flood scenario, how many Stellenbosch Population will be affected' should be 'In the event of this Stellenbosch flood scenario, how many Stellenbosch people will (or may or could?) be affected' (or 'what Stellenbosch Population')

I don't think I'm able to fix this quickly. This header is coming from InaSAFE logic/concept called 'question'. IIRC, in InaSAFE v 3.5 we generate this header (from InaSAFE library) by concatenating layer title. So it is dependant on the layer title it self and the template/logic from InaSAFE lib.

**Comment by gubuntu** [comment]
>         dont'save / save just switch between each other and the dialog only disappears when clicking somewhere else
> 
> See above, this is because it is just a toggle to mark, either the analysis should be kept or not for the day onwards.

Still not intuitive, how can we make it clearer to the user?

> 
>         Change home page button hover to 'To home page' from 'to geonode home page'
> 
> I can do this quickly

Please do so

> 
>         Once an analysis has bene Saved, why does the Save button keep appearing?
> 
> Ah yes, maybe it is a bit confusing for this representations. So, in the ticket I suggest that we should change this to a checkmark or something, so the user know that this is an option, not action.

Please do so

**Comment by gubuntu** [comment]
these have all been addressed by other issues
