### ISSUE TITLE
We need to highlight the possible browser issues

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#64]
The possible browser issues are not highlighted.
We need to create a warning for the user about the possible issues for his browser.

**Comment by boney-bun** [comment]
according to [this website](http://outdatedbrowser.com/en), these are old-fashioned browsers:
- firefox < 53
- chrome <58
- IE < 11
- safari < 10
- opera < 44

Proposed solutions:
- add [outdated-browser](https://github.com/burocratik/outdated-browser) library and it will show the message.
- show a pop up javascript window telling the users to upgrade their browsers.
- redirect users to a page asking to upgrade their browsers, but still give the users a chance to proceed visiting the website.

which one do you prefer @gubuntu @MariaSolovyeva ?

**Comment by gubuntu** [comment]
third optin please @boney-bun

**Comment by boney-bun** [comment]
I am thinking the third option may consume more resource as it load the whole page. so I go with the second option using js and show a pop up window. 
basically, the code checks:
* if the browser comply with [ECMA Script 5](https://en.wikipedia.org/wiki/ECMAScript#5th_Edition) 
* if the browser accepts a json file.
however, the code didn't check if javascript is enabled or not in the browser. there are too many things to consider for browser compatibility. that's why I just focus on the two condition above.
The screenshot is below:
![geosafe64](https://cloud.githubusercontent.com/assets/4602383/25851311/67716922-3519-11e7-809d-934b0b7d76d8.gif)
* The first scenario: the user browser is compatible, nothing to show.
* The second scenario ( i modified the code for the demo. that's why there is one second pause in the gif): the user's browser is not compatible. a pop up window will keep showing the message when the user clicks on a link.

**Comment by gubuntu** [comment]
seems OK to me

**Comment by boney-bun** [comment]
PR is on kartoza/geonode#209

**Comment by boney-bun** [comment]
sorry, but I have to withdraw the previous PR.
geonode has checked browser compatibility, particularly using IE.
moving the code from geonode to geosafe.
Browser compatibility is now on geosafe's create analysis page as it relies heavily on javascript.
here is the illustration of the code:
![geosafe64](https://cloud.githubusercontent.com/assets/4602383/26665309/d016b650-46ec-11e7-899d-cbbd1ccd609b.gif)
