### ISSUE TITLE
Analysis page layer legend

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#71]
After the layer is selected, the user needs to see the legend about the colors used in this layer.

![layer_colors](https://cloud.githubusercontent.com/assets/10400420/24194700/1b34b71c-0f08-11e7-8bdb-ef91cce8b7f5.png)

Proposed solution: to add the legend in the bottom right corner with the possibility to minimize it and expand back up.

**Comment by gubuntu** [comment]
put legend with transparency slider from #101. Use GeoNode API (?) or WMS GetLegendGraphic request to obtain the legend, just like the GeoNode layer page does (except without GeoExt)

**Comment by boney-bun** [comment]
I'm working towards integrating Tim's WMS Legend into the code.
find the library from [here](https://github.com/kartoza/leaflet-wms-legend)

**Comment by boney-bun** [comment]
here is the mockup for the legend (the legend is on the top right corner):
![legend71](https://cloud.githubusercontent.com/assets/4602383/26543507/53c50ff2-44b2-11e7-988f-778387f77bb8.gif)

two issues need to be sorted out:
* the cosmetique of the page
* the legend of nsunga_tanzania is not shown up. I think because no legend define?

what do you think of the mockup @gubuntu ?

**Comment by Gustry** [comment]
Every layers should have a legend, even if it's black and white. Are you using the getLegendGraphic ?
The legend provided by the QGIS Server app in geonode works ?

**Comment by boney-bun** [comment]
Yes, I am. I use the API from [qgis server](https://github.com/kartoza/geonode/blob/master-qgis_server/geonode/qgis_server/views.py). the legend comes from png obtained from the legend function on the backend.

**Comment by gubuntu** [comment]
Legen graphics working nicely.
