### ISSUE TITLE
Report buttons

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#73]
- [ ] We need to keep only 1 or two buttons in order not to confuse the user.  For example, one for “More details”, another for “Download”.
![buttons](https://cloud.githubusercontent.com/assets/10400420/24198926/e1e6aa68-0f18-11e7-9098-88dbf807284d.png)

- [ ] “Show map report” - Opens a pop-up with the title “Impact report”. We need to update the title or the button name (if we keep this one)
![report](https://cloud.githubusercontent.com/assets/10400420/24198831/88c7cc0a-0f18-11e7-9036-963d4bbb63b8.png)

**Comment by boney-bun** [comment]
It seems that the UI has changed in Geonode 2.6a1. This issue is no longer valid, except if we decide to keep using Geonode 2.4.

**Comment by gubuntu** [comment]
@boney-bun please paste screenshots of 2.6 to show the problem solved

**Comment by boney-bun** [comment]
@gubuntu here is the screenshot:
 
![screen shot 2017-04-10 at 10 37 28 pm](https://cloud.githubusercontent.com/assets/4602383/24858020/7f58d756-1e3e-11e7-843b-2d542fe2d8af.png)

**Comment by gubuntu** [comment]
@lucernae please close if you can confirm that the view in 2.6 above has indeed replaced the same view in 2.4 OP.

**Comment by gubuntu** [comment]
@lucernae I'm going to assume this is correct and close it

**Comment by gubuntu** [comment]
test again on staging with real data to confirm

**Comment by boney-bun** [comment]
I suggest to remove 2 buttons: "download layer" and "layer detail". 
"Download layer" button can be found in another page. 
"Layer detail" button can be removed as it specifies on the two reports as well.
Impact Report (was: "Show Map Report" button) shows different information in comparison to "Show table report" button, so we should keep both of them. 
I think when a user clicks on "Show Analysis Summary" button, the user expect to get the reports and is able to download it.
So, the three buttons need to be there.
The new UI will be:
![screen shot 2017-05-29 at 11 57 59 pm](https://cloud.githubusercontent.com/assets/4602383/26548991/e121c292-44ca-11e7-98de-be05124d5d15.png)

**Comment by gubuntu** [comment]
My suggestions, keep three with these labels:
- Impact report
- Table report
- Impact layer

- Save...if clicked, show 'Analysis saved' (unless user is not logged in - get message saying they must log in to save analysis; in fact if not logged in, Save should become 'log in to Save')
 - plus a button 'Cancel Save', which, if clicked, returns 'Analysis won't be saved'

- Add 'Close' button or 'X' so it's clear to user how to close when done. They can also click anywhere else to close but that's not intuitive. 

@boney please implement as far as you can, ask @lucernae if you struggle to hook the buttons to the correct backend actions.

**Comment by boney-bun** [comment]
below is the mockup what happened when a `save` button is clicked:
![reportbutton73](https://user-images.githubusercontent.com/4602383/27946405-d57f4c2e-631b-11e7-88ac-8902998f60f5.gif)

when a user not sign in, the mockup is:
![screen shot 2017-07-07 at 1 29 25 pm](https://user-images.githubusercontent.com/4602383/27945696-6042ccf4-6318-11e7-861a-996cd083b787.png)

my question is: what's the difference in logic between `don't save`  and `Cancel Save` buttons?

**Comment by lucernae** [comment]
Maybe I can explain a little bit:

> Save...if clicked, show 'Analysis saved' (unless user is not logged in - get message saying they must log in to save analysis; in fact if not logged in, Save should become 'log in to Save')

The original specification about that button is: that is a toggle button. So when it showed as `Save` that mean the analysis will be kept. `Don't save` means it will not be kept and will be deleted nightly. So the first gif doesn't show the correct information. What I already commented since long ago is, this button is misleading because the option is binary. Even if we make like an android toggle button it will still not be clear. What I suggest is make this button as an ordinary checkbox with Label. So user will know checked means analysis will be kept. Doing uncheck or check will show the message (or show a toast info).
If user is not logged in, we can still show the checkbox, but it will be disabled (default to unchecked), and show a button to ask to login to enable the checkbox (Log in to keep analysis).

> plus a button 'Cancel Save', which, if clicked, returns 'Analysis won't be saved'

With the previous suggestion, this won't be necessary.

> Add 'Close' button or 'X' so it's clear to user how to close when done. They can also click anywhere else to close but that's not intuitive.

There is an X mark on top right corner, but I agree we can add another button with Close label.

- For the Impact Report and Table Report download. I suggest to make that button grouped inside Download Report, like this one: http://getbootstrap.com/components/#btn-dropdowns-single. Because I think Maria's suggestion makes sense, we should not put too many buttons to confuse user.

**Comment by gubuntu** [comment]
@boney-bun please implement as @lucernae suggests

**Comment by boney-bun** [comment]
let me know what's your opinion @gubuntu @lucernae ?
![reportbutton73](https://user-images.githubusercontent.com/4602383/27983800-88520a02-63ef-11e7-955f-d9cf50af3839.gif)

**Comment by gubuntu** [comment]
LGTM
