### ISSUE TITLE
List of analysis page table

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#77]
The table head - “Impact layer” should be called “Result”
![list-of-analysis](https://cloud.githubusercontent.com/assets/10400420/24199772/f4d53358-0f1b-11e7-906f-6a13db1712e1.png)

**Comment by gubuntu** [comment]
nice @boney-bun.
 
The way we work with GitHub in Kartoza is that you fork a repo into your own account (boney-bun/geosafe) and develop on that. Then when you're done you make a pull request (PR) against upstream (kartoza/geosafe). This gives others a chance to review your code (if necessary). Otherwise you merge the PR. 

Please also use screenshots to illustrate the results of your work

**Comment by ismailsunni** [comment]
@gubuntu I think it's a good practice also to protect the develop branch (master also), so that we can prevent direct commit to master/develop branch.

**Comment by boney-bun** [comment]
Thanks for reminding me @gubuntu 
I have done exactly as your suggestion.

Should I undo the commit?

![screen shot 2017-04-02 at 8 52 36 pm](https://cloud.githubusercontent.com/assets/4602383/24595084/400ea380-1887-11e7-9590-6b708efd9fbc.png)

**Comment by gubuntu** [comment]
Thanks @boney-bun. If you've merged the same change via a PR, I think in this case you can just leave it. I'd rather not risk you undoing a commit that you've already pushed. 

@ismailsunni is this procedure written up anywhere yet? So we can just point new (and existing) devs to it.

**Comment by lucernae** [comment]
> @ismailsunni is this procedure written up anywhere yet? So we can just point new (and existing) devs to it.

I guess not, because we consider it as standard practice everywhere.

> @gubuntu I think it's a good practice also to protect the develop branch (master also), so that we can prevent direct commit to master/develop branch.

Thank's, done for develop. We are using 2.6.x branches now as develop, so I forgot to protect develop branch.

> Thanks @boney-bun. If you've merged the same change via a PR, I think in this case you can just leave it. I'd rather not risk you undoing a commit that you've already pushed.

That's ok, I will take care of it. From now @boney-bun , just create PR first. Our main develop branch for this sprint is branch **2.6.x**. I made it as default.

**Comment by gubuntu** [comment]
@lucernae please close if done
