### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#80]
The font size is small. It may be difficult for old people to read.
We should increase the body font size up to 16px.

**Comment by boney-bun** [comment]
is this issue still valid as the UI has changed in geonode 2.6a?

**Comment by gubuntu** [comment]
@boney-bun please post a screenshot of the font looking big enough in 2.6, then you can close if it is indeed fixed

**Comment by boney-bun** [comment]
@gubuntu the font was  small in Geonode 2.4 and it had a text link to help new users. The UI has changed in Geonode 2.6a, particularly it has "Getting Started" button (instead of the text link) now.

Here is the screenshot:

![screen shot 2017-04-10 at 8 31 46 pm](https://cloud.githubusercontent.com/assets/4602383/24852951/6f8410b8-1e2d-11e7-918e-ce9d4e9f354d.png)

**Comment by gubuntu** [comment]
pls also confirm that the text in GeoSAFE is big enough too, thanks.

**Comment by boney-bun** [comment]
Yes, it is big enough. I would close the issue then. thanks.
