### ISSUE TITLE
Layers naming

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#85]
Inconsistent naming convention (using space for “Indonesia volcano KRB” and underscore for “flood_scenario on buildings”)

![naming2](https://cloud.githubusercontent.com/assets/10400420/24294891/7355a9e0-10a9-11e7-8369-943d687f1925.png)

**Comment by boney-bun** [comment]
It seems that the layer names come from the uploaded files.
The possible solution:
1. If we want to impose the naming convention, we can check and modify the name accordingly when a user upload a file.
2. the user can manually rename the name by manually editing them.
3. we can reformat the layers’ name when displaying them. It serves solely for cosmetic. We can do this by removing underscore (and maybe any metacharacter) found in the layers' name.

**Comment by lucernae** [comment]
Hi, this is just name that the user specifies.
By default, the name will be taken from layer name.

I suggest we close this ticket because:

1. User are able to change the name themselves by editing the layer via GeoNode interface
2. We are already able to rename Analysis layer when we first run it.
